# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_fields_startups_and_tags_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_Post', 'can view unpublished Post'),), 'verbose_name': 'blog post'},
        ),
    ]
