# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_view_future_post_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_post', 'Can view unpublished Post'),), 'verbose_name': 'blog post'},
        ),
    ]
