# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:21
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.db import migrations, models

def generate_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    try:
        Permission.objects.get(codename='add_post', content_type__app_label='blog')
    except Permission.DoesNotExist:
        models_module = getattr(apps, 'models_module', None)
        if models_module is None:
            apps.models_module = True
            create_permissions(apps, verbosity=0)
            apps.models_module = None
        else:
            raise

def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('blog', '0005_auto_20171220_0927'),
    ]

    operations = [
        migrations.RunPython(generate_permissions, reverse_code, )
    ]
