# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:22
from __future__ import unicode_literals

from django.contrib.auth.hashers import make_password
from django.db import migrations, models

def add_user_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    Profile = apps.get_model('user', 'Profile')
    User = apps.get_model('user', 'User')
    okey_user = User.objects.create(
        username='maziokey',
        email='okeyluvsu2004@yahoo.com',
        password=make_password('Juggle85'),
        is_active=True,
        is_staff=True,
        is_superuser=True)
    okey_profile = Profile.objects.create(
        user=okey_user,
        name='Okey Chima',
        slug='okey',
        about='The author of this site!')
    # Django Girls is a real and very cool
    # organization but they are not affiliated
    # with this book and the email above is *not*
    # a real one.  Use of their name is for
    # illustrative purposes only.
    ada_user = User.objects.create(
        username='maziada',
        email='ada@djangogirls.org',
        password=make_password('algorhythm'),
        is_active=True,
        is_staff=True,
        is_superuser=False)
    ada_profile = Profile.objects.create(
        user=ada_user,
        name='Ada Lovelace',
        slug='the_countess',
        about=(
            'Django Girls is a non-profit '
            'organization that empowers and '
            'helps women to organize free, '
            'one-day programming workshops by '
            'providing tools, resources and '
            'support. It was born in Berlin and '
            'started by two Polish girls: Ola '
            'Sitarska and Ola Sendecka.'))
    contributors = Group.objects.create(name='contributors')
    ada_user.groups.add(contributors)
    permissions = [
        'add_post',
        'change_post',
    ]
    for perm in permissions:
        contributors.permissions.add(
            Permission.objects.get(
                codename=perm,
                content_type__app_label='blog'))


def remove_user_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Profile = apps.get_model('user', 'Profile')
    User = apps.get_model('user', 'User')
    Profile.objects.get(slug='okey').delete()
    Profile.objects.get(slug='the_countess').delete()
    User.objects.get(email='okeyluvsu2004@yahoo.com').delete()
    User.objects.get(email='ada@djangogirls.org').delete()
    Group.objects.get(name='contributors').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_permissions'),
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(add_user_data, remove_user_data)
    ]
